title: Florence Ko Studio
description: Florence Ko music studio

url: http://kerryzhou.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: florenceko
   twitter: florenceko
   facebook: florenceko
   email: florenceko6@yahoo.com

google_analytics: "UA-58263416-1"
